[package]
name = "cargo-info"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
cargo_metadata = "0.12"
structopt = "0.3"
tabwriter = "1.2"
